# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/product.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/product.proto\x12\x07product\"r\n\x0eProductRequest\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\x12\x10\n\x08sucursal\x18\x05 \x01(\t\x12\x0c\n\x04\x66oto\x18\x06 \x01(\x0c\"A\n\x0fProductResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t2X\n\x0eProductService\x12\x46\n\x0fValidateProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=32
  _globals['_PRODUCTREQUEST']._serialized_end=146
  _globals['_PRODUCTRESPONSE']._serialized_start=148
  _globals['_PRODUCTRESPONSE']._serialized_end=213
  _globals['_PRODUCTSERVICE']._serialized_start=215
  _globals['_PRODUCTSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
